return {
	"r-cha/encourage.nvim",
	event = { "BufWrite" },
	opts = {
		messages = {
			"頑張れよ",
			"これからだよ",
			"まだまだだよ",
			"光の方へ",
			"明るい未来え",
			"確乎不抜",
			"外柔内剛",
			"だってばよ",
			"だめだめだめ",
			"諦めないよ",
			"絶対出来るよ",
			"We will fail when we fail to try.",
			"If you want to lift yourself up, lift up someone else.",
			"Through discipline comes freedom.",
			"Don’t be afraid to give up the good to go for the great.",
			"Encouragement is like water to the soul, it makes everything grow.",
			"It is during our darkest moments that we must focus to see the light.",
			"You cannot expect victory and plan for defeat.",
			"It always seems impossible until it’s done.",
			"When you have a dream, you've got to grab it and never let go.",
			"To love oneself is the beginning of a lifelong romance.",
			"Bet on me? Bet I will.",
			"Make each day your masterpiece.",
			"Don’t count the days, make the days count.",
			"Light tomorrow with today.",
			"Believe you can and you're halfway there.",
			"Don’t sit down and wait for the opportunities to come. Get up and make them.",
			"Failure is the condiment that gives success its flavor.",
			"Never confuse a single defeat with a final defeat.",
			"Never allow a person to tell you no who doesn’t have the power to say yes.",
			"It takes courage to grow up and become who you really are.",
			"The individual who says it is not possible should move out of the way of those doing it.",
			"Success is the sum of small efforts repeated day in and day out.",
		},
	},
}
